spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    #url: jdbc:mysql://localhost:3306/mydb
    url: jdbc:mysql://demo-db/demo_db
    username: sasha
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.mail.ru
    port: 465
    username: "se16052000@mail.ru"
    password: "f6hgzc3RiZD2hvLBNHrB"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: smtp.mail.ru
    protocol: smtps
    default-encoding: UTF-8
    test-connection: false
    tls: true
    debug: true
  freemarker.template-loader-path: classpath:/templates
  freemarker.suffix: .ftlh
  host: 37.193.83.22
ontology:
  filename: "../demo-ontology/LearnerModel_LAST.owl"